[package]
name = "snake"
version = "0.1.0"
authors = ["Octave Larose <octave.larose@hotmail.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
sdl2 = "0.34.3"
